# Generated by Django 5.1 on 2024-08-30 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_job_category'),
    ]

    operations = [
    ]
